### ISSUE TITLE
แจ้งปัญหา หลังจากทดสอบกับเว็บตัวอย่างแล้ว

### ISSUE THREAD

**Issue by goragodwiriya** [narate/g6#1]
แจ้งปัญหา หลังจากทดสอบกับเว็บตัวอย่างแล้ว
1.ยิงไปที่ไหนก็ไม่ได้เลย ที่เห็นยิงได้ก็มี i.dont.works
2.เมื่อยมือ

**Comment by narate** [comment]
@goragod  ขอตัวอย่าง URL ที่ยิงไปไม่ได้ครับ หรือสามารถส่ง Pull Request มาได้เลยครับ

**Comment by narate** [comment]
จากปัญหาที่แจ้งมา ผมทดสอบที่ URL ที่คาดว่าอาจจะมีปัญหาคือ  https://www.goragod.com/ ถ้าเปิด Dev Tools เพื่อดู จะเห็น error

```
Access to fetch at 'https://www.goragod.com/' from origin 'https://narate.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
ตามภาพ

![image](https://user-images.githubusercontent.com/857868/101313373-987d7a80-3888-11eb-85fa-36e9b60c29e3.png)

ซึ่งปัญหานี้ ระบุไว้แล้วใน [Known issue](https://github.com/narate/g6#known-issue) "Target URL must allow CORS"

ถ้าปัญหาที่แจ้งมา ไม่ใช่ปัญหานี้ สามารถเปิด issue นี้ใหม่ได้เลยครับ ซึ่งตั้งใจที่จะเป็นแบบนี้ แต่จากข้อความ

```
set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
เราสามารถ เพิ่ม `mode: 'no-cors'`. ให้ `fetch` ได้ เดี๋ยวผมทดสอบ แล้วมาอัปเดต

ส่วนข้อ 2 เมื่อยมือ อันนี้มันเป็นฟีเจอร์ครับ แค่ขยับ ก็เท่ากับ Load Test

**Comment by narate** [comment]
จากการทดลองใช้ `mode: 'no-cors'` ปัญหาที่ตามมาคือ ไม่สามารถอ่าน header, status code, body ได้ ปัญหานี้เลยไม่สามารถแก้ไขได้ และเป็น [Known issue ](https://github.com/narate/g6#known-issue)
